### ISSUE TITLE
Missing hostname during dispatch causes TypeError : preg_match() expects parameter 2 to be string, null given

### ISSUE THREAD

**Issue by lklapa** [laminas/laminas-router#20]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.0

#### Summary

After upgrading `laminas-router` from `3.3.2` to `3.4.0` tests from `laminas-test` that use `$this->dispatch('/some/action')` no longer work.

#### Previous behavior

On `3.3.2` the tests using `$this->dispatch('/some/action')` work properly.

#### Current behavior

The result of `$this->dispatch('/some/action');` is:

`TypeError : preg_match() expects parameter 2 to be string, null given
 /var/www/vendor/laminas/laminas-router/src/Http/Hostname.php:294`

#### How to reproduce

1. Update `laminas-router` to `3.4.0`
2. Run a test that uses `$this->dispatch('/some/action');`

Note that using `$this->dispatch('http://whatever/some/action');` does work on `3.4.0`. I understand there is no hostname in `$this->dispatch('/some/action')`, but not sure if the changes introduced in `3.4.0` were expected to cause a BC break. If yes, maybe the documentation simply needs updating.

**Comment by weierophinney** [comment]
Fixed with #21
