### ISSUE TITLE
Wildcard: TypeError: rawurlencode() expects parameter 1 to be string, int given

### ISSUE THREAD

**Issue by gkralik** [laminas/laminas-router#23]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.0

#### Summary

Starting from version 3.4.0, the Wildcard route throws a `TypeError` when passing int parameters to `rawurlencode()`. This has previously worked just fine (up to version 3.3.2). It seems a cast to string is missing before encoding parameter values. It looks like the culprit could be zendframework/zend-router#44.

It looks like a similar problem as #14 

Tested on PHP 7.3 and PHP 7.4

#### Previous behavior

No TypeError is thrown when passing `int` params to `Wildcard::assemble()`.

#### Current behavior

When passing `int` params to `Wildcard::assemble()`, a `TypeError` is thrown when invoking `rawurlencode()`.

#### How to reproduce

```php
$wildcard = new \Laminas\Router\Http\Wildcard();

echo $wildcard->assemble([
    'int_param' => 1,
]);

// throws TypeError: rawurlencode() expects parameter 1 to be string, int given
```

**Comment by weierophinney** [comment]
Fixed with #24
