### ISSUE TITLE
PHP 8.2:  Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by matbech** [laminas/laminas-router#39]
Error message:
```PHP Deprecated:  Creation of dynamic property Laminas\Router\Http\Part::$priority is deprecated in vendor\laminas\laminas-router\src\Http\TreeRouteStack.php on line 228```

File:
https://github.com/laminas/laminas-router/blob/3.7.x/src/Http/TreeRouteStack.php#L228

Cause
Dynamic properties are deprecated with PHP 8.2:
https://php.watch/rfcs/deprecate_dynamic_properties

**Comment by Ocramius** [comment]
Note: PHP 8.2 is not yet supporters by this component.

Still, feel free to send a patch 👍

**Comment by matbech** [comment]
PR: https://github.com/laminas/laminas-router/pull/40
