### ISSUE TITLE
Wildcard no longer works when route ends on slash

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-router#4]
One can reproduce this using:

```php
$request = new \Zend\Http\Request;
$request->setUri('http://www.test.nl/bla/');

$route = \Zend\Router\Http\Wildcard::factory([]);
$match = $route->match($request);

// Now `$match === null`
```

Was introduced in https://github.com/zendframework/zend-router/pull/47 by @weierophinney 

---

Originally posted by @roelvanduijnhoven at https://github.com/zendframework/zend-router/issues/49

**Comment by weierophinney** [comment]
Excuse me; I think this _bug_ was not recently introduced. But matches existing behaviour.

As this will be deprecated; feel free to close.

I'll roll my own wildcard implementation for now that simply consumes the remainder of the path.

---

Originally posted by @roelvanduijnhoven at https://github.com/zendframework/zend-router/issues/49#issuecomment-402464329

**Comment by weierophinney** [comment]
Reference for anybody looking for something like what I described:

```php
class MatchEverything implements RouteInterface
{
    /** @var array */
    private $defaults;

    public function __construct(array $defaults)
    {
        $this->defaults = $defaults;
    }

    public function getAssembledParams()
    {
        return [];
    }

    public static function factory($options = [])
    {
        return new self($options['defaults'] ?? []);
    }

    public function match(Request $request, $pathOffset = null)
    {
        if (!method_exists($request, 'getUri')) {
            return null;
        }

        $remainder = substr($request->getUri()->getPath(), $pathOffset);

        return new RouteMatch($this->defaults, strlen($remainder));
    }

    public function assemble(array $params = [], array $options = [])
    {
        return '';
    }
}
```

---

Originally posted by @roelvanduijnhoven at https://github.com/zendframework/zend-router/issues/49#issuecomment-402464572

**Comment by samsonasik** [comment]
I am closing it as wildcard is deprecated
